### ISSUE TITLE
icanhazip.com returns external IPv6 address...

### ISSUE THREAD

**Issue by Confuseh** [jamesan/auto-xflux#2]
icanhazip.com returns external IPv6 address which is not compatible with geocodeip.com

**Comment by jamesan** [comment]
I've just switched geolocation providers in b4c3c3a of #4 as @cfcosta claims icanhazip.com is sometimes offline and suggested ipinfo.io as it directly geolocates replacing the original two-call process. I'm going to close this and mark it as wontfix as it no longer applies.
